services:
  ordertest.api:
    image: ordertest.api
    build:
      context: .
      dockerfile: OrderTest.API/Dockerfile
    networks:
      - application-network
    ports:
      - "8080:8080"
    depends_on:
      - postgres.db
  postgres.db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=Orders.db
    ports:
      - "5432:5432"
    networks:
      - application-network
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8081:80"
    networks:
      - application-network
    depends_on: 
      - ordertest.api
networks:
  application-network:
